# Generated by Django 5.1.6 on 2025-03-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_availablestore_product_rating_product_total_review_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/ads-banner/')),
                ('unit', models.CharField(max_length=10)),
                ('prie', models.PositiveIntegerField()),
            ],
        ),
    ]
