# Generated by Django 5.1.6 on 2025-03-05 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_adsbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='adsbanner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
