# Generated by Django 5.1.6 on 2025-03-05 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_adsbanner_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdsBanner',
        ),
    ]
