# Generated by Django 5.1.6 on 2025-03-02 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourtestimonial',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
