# Generated by Django 5.1.6 on 2025-03-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_ourtestimonial_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentmanagementsettings',
            name='secondary_logo',
            field=models.ImageField(blank=True, null=True, upload_to='image/logo/'),
        ),
    ]
