# Generated by Django 5.1.6 on 2025-03-04 05:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contentmanagementsettings_secondary_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='image/partner-logo/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='contentmanagementsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contentmanagementsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
