# Generated by Django 5.1.6 on 2025-03-04 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_ourpartner_contentmanagementsettings_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourpartner',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='image/partner-logo/'),
        ),
    ]
