# Generated by Django 5.1.6 on 2025-03-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=155, null=True)),
                ('designation', models.CharField(max_length=55)),
                ('message', models.TextField(blank=True, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='image/team/')),
            ],
        ),
        migrations.AddField(
            model_name='contentmanagementsettings',
            name='video_content',
            field=models.FileField(blank=True, null=True, upload_to='video/home-content/'),
        ),
        migrations.AddField(
            model_name='contentmanagementsettings',
            name='whatspp_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
