# Generated by Django 5.1.6 on 2025-03-05 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_ourteam_contentmanagementsettings_video_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardSection01',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/card-section-01/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='discountcard',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
