# Generated by Django 5.1.6 on 2025-03-05 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_adsbanner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adsbanner',
            old_name='prie',
            new_name='price',
        ),
    ]
