# Generated by Django 5.1.6 on 2025-03-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_prie_adsbanner_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adsbanner',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
