# Generated by Django 5.1.6 on 2025-03-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_adsbanner_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardsection01',
            name='image',
        ),
        migrations.AddField(
            model_name='cardsection01',
            name='icon',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
